server {
    listen 80;
    server_name .hxi.am;
    server_tokens off;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name .hxi.am;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/qurl.sh/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qurl.sh/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;

    location /api/ {
        # Use Docker's embedded DNS resolver
        resolver 127.0.0.11 valid=30s;
        set $upstream_hxiam_api hxiam_api;
        proxy_pass http://$upstream_hxiam_api:3000;
        
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $http_cf_connecting_ip;
        proxy_set_header    X-Forwarded-For     $http_cf_connecting_ip;
        proxy_set_header    X-Forwarded-Proto   https;
    }

    location / {
        # Use Docker's embedded DNS resolver
        resolver 127.0.0.11 valid=30s;
        set $upstream_hxiam hxiam_web;
        proxy_pass http://$upstream_hxiam:3000;
        
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $http_cf_connecting_ip;
        proxy_set_header    X-Forwarded-For     $http_cf_connecting_ip;
        proxy_set_header    X-Forwarded-Proto   https;
    }
}
